"""Mixer Model and Validation: Convert Required Fields into Optional Fields

Revision ID: 07cb97870a01
Revises: d986b0f4d7b6
Create Date: 2025-08-28 10:07:05.899398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07cb97870a01'
down_revision: Union[str, Sequence[str], None] = 'd986b0f4d7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('tbl_mixer_details', 'cleaning_time_start',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('tbl_mixer_details', 'cleaning_time_end',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('tbl_mixer_details', 'cleaning_rm_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tbl_mixer_details', 'cleaning_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_time_start',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_time_end',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_rm_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_tbl_mixer_details', 'cleaning_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_rm_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_time_end',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('temp_tbl_mixer_details', 'cleaning_time_start',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('tbl_mixer_details', 'cleaning_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tbl_mixer_details', 'cleaning_rm_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tbl_mixer_details', 'cleaning_time_end',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('tbl_mixer_details', 'cleaning_time_start',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    # ### end Alembic commands ###
