"""tbl_extruder_machine_details: modified the is_vacuum_on

Revision ID: 0fcc7db6b63b
Revises: c0abbbd21168
Create Date: 2025-10-23 09:49:09.693711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcc7db6b63b'
down_revision: Union[str, Sequence[str], None] = 'c0abbbd21168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_machine_details', sa.Column('is_vacuum_on', sa.Boolean(), nullable=False))
    op.drop_column('tbl_extruder_machine_details', 'is_vaccumeon')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.add_column('tbl_extruder_machine_details', sa.Column('is_vaccumeon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tbl_extruder_machine_details', 'is_vacuum_on')
    # ### end Alembic commands ###
