"""tbl_extruder_purging_headers: make the palletizer, siever, and resin to optional

Revision ID: 118186013ed7
Revises: ac445b5499dc
Create Date: 2025-10-30 15:00:47.834513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118186013ed7'
down_revision: Union[str, Sequence[str], None] = 'ac445b5499dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_extruder_purging_headers', 'resin_used_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.alter_column('tbl_extruder_purging_headers', 'resin_used_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
