"""Created the initial table for the Extruder Module

Revision ID: 1398ba93aea1
Revises: 1bae561f1a10
Create Date: 2025-09-24 15:33:47.130215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1398ba93aea1'
down_revision: Union[str, Sequence[str], None] = '1bae561f1a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_extruder_machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_machines_name'), 'tbl_extruder_machines', ['name'], unique=True)
    op.create_table('tbl_extruder_resins',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_resins_name'), 'tbl_extruder_resins', ['name'], unique=True)
    op.create_table('tbl_extruder_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_zones_name'), 'tbl_extruder_zones', ['name'], unique=True)
    op.create_table('tbl_extruder_resin_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resin_id', sa.SmallInteger(), nullable=False),
    sa.Column('motor_rpm', sa.String(length=50), nullable=False),
    sa.Column('feed_rate', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['resin_id'], ['tbl_extruder_resins.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_extruder_processing_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('resin_params_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('temp_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['tbl_extruder_machines.id'], ),
    sa.ForeignKeyConstraint(['resin_params_id'], ['tbl_extruder_resin_params.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['tbl_extruder_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'resin_params_id', 'zone_id', name='_machine_resin_zone_uc')
    )
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_table('tbl_extruder_processing_params')
    op.drop_table('tbl_extruder_resin_params')
    op.drop_index(op.f('ix_tbl_extruder_zones_name'), table_name='tbl_extruder_zones')
    op.drop_table('tbl_extruder_zones')
    op.drop_index(op.f('ix_tbl_extruder_resins_name'), table_name='tbl_extruder_resins')
    op.drop_table('tbl_extruder_resins')
    op.drop_index(op.f('ix_tbl_extruder_machines_name'), table_name='tbl_extruder_machines')
    op.drop_table('tbl_extruder_machines')
    # ### end Alembic commands ###
