"""tbl_extuder_purging_details: added notes column in the table

Revision ID: 14e519fb4b6b
Revises: 8950948c036a
Create Date: 2025-10-23 16:06:15.297758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e519fb4b6b'
down_revision: Union[str, Sequence[str], None] = '8950948c036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_purging_details', sa.Column('notes', sa.String(length=250), nullable=True))
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_column('tbl_extruder_purging_details', 'notes')
    # ### end Alembic commands ###
