"""add: tbl_extruder_old_amiel_data and tbl_extruder_old_excel_data

Revision ID: 209465908bd4
Revises: 118186013ed7
Create Date: 2025-11-25 10:49:07.849738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '209465908bd4'
down_revision: Union[str, Sequence[str], None] = '118186013ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_extruder_old_amiel_data',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('qty_order', sa.Numeric(), nullable=True),
    sa.Column('total_output', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Numeric(), nullable=True),
    sa.Column('time_start', postgresql.ARRAY(sa.DateTime()), nullable=True),
    sa.Column('time_end', postgresql.ARRAY(sa.DateTime()), nullable=True),
    sa.Column('output_percent', sa.Numeric(), nullable=True),
    sa.Column('loss', sa.Numeric(), nullable=True),
    sa.Column('loss_percent', sa.Numeric(), nullable=True),
    sa.Column('purging', sa.String(), nullable=True),
    sa.Column('resin', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('screw_config', sa.String(), nullable=True),
    sa.Column('feed_rate', sa.Numeric(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('screen_size', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('supervisor', sa.String(), nullable=True),
    sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('temperature', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('purge_duration', sa.Integer(), nullable=True),
    sa.Column('outputs', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('output_per_hour', sa.Numeric(), nullable=True),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('total_input', sa.Numeric(), nullable=True),
    sa.Column('lot_number', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.Column('updatedBy', sa.String(), nullable=True),
    sa.Column('resin_quantity', sa.Numeric(), nullable=True),
    sa.Column('encoded_on', sa.Date(), nullable=True),
    sa.Column('machine_start', sa.DateTime(), nullable=True),
    sa.Column('machine_off', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_table('tbl_extruder_old_amiel_data')
    # ### end Alembic commands ###
