"""Cretion Other Tables

Revision ID: 58818c0ed744
Revises: 2386522d1a78
Create Date: 2025-10-22 10:04:44.252979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58818c0ed744'
down_revision: Union[str, Sequence[str], None] = '2386522d1a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_extruder_machine_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('screen_size_id', sa.Integer(), nullable=False),
    sa.Column('screw_config', sa.String(length=255), nullable=True),
    sa.Column('feed_rate', sa.String(length=100), nullable=True),
    sa.Column('rpm', sa.String(length=100), nullable=True),
    sa.Column('machine_datetime_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('machine_datetime_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['screen_size_id'], ['tbl_extruder_screen_sizes.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tbl_extruder_machine_configs')
    op.add_column('tbl_extruder_form_data', sa.Column('qty_produced', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tbl_extruder_form_data', sa.Column('machine_details_id', sa.Integer(), nullable=False))
    op.add_column('tbl_extruder_form_data', sa.Column('shift_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tbl_extruder_form_data_machine_id_fkey'), 'tbl_extruder_form_data', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_extruder_form_data', 'tbl_extruder_machine_details', ['machine_details_id'], ['id'])
    op.create_foreign_key(None, 'tbl_extruder_form_data', 'tbl_extruder_shifts', ['shift_id'], ['id'])
    op.drop_column('tbl_extruder_form_data', 'machine_id')
    op.drop_column('tbl_extruder_form_data', 'total_input')
    op.add_column('tbl_extruder_machine_temps', sa.Column('zone_id', sa.Integer(), nullable=False))
    op.add_column('tbl_extruder_machine_temps', sa.Column('temp_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('tbl_extruder_machine_temps', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tbl_extruder_machine_temps', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_extruder_machine_temps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_machine_temps', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_machine_temps', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_machine_temps', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_extruder_machine_temps', 'users', ['deleted_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_machine_temps', 'users', ['created_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_machine_temps', 'tbl_extruder_zones', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'tbl_extruder_machine_temps', 'users', ['updated_by_id'], ['user_id'])
    op.add_column('tbl_extruder_outputs', sa.Column('time_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('time_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('qty_output', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('qty_loss', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tbl_extruder_outputs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_extruder_outputs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_extruder_outputs', 'users', ['deleted_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_outputs', 'users', ['updated_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_outputs', 'users', ['created_by_id'], ['user_id'])
    op.add_column('tbl_extruder_personnels', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('tbl_extruder_personnels', sa.Column('position_id', sa.Integer(), nullable=False))
    op.add_column('tbl_extruder_personnels', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tbl_extruder_personnels', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_extruder_personnels', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_personnels', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_personnels', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_personnels', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_extruder_personnels', 'users', ['created_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_personnels', 'users', ['deleted_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_personnels', 'users', ['updated_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_personnels', 'tbl_production_employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'tbl_extruder_personnels', 'tbl_employee_positions', ['position_id'], ['id'])
    op.add_column('tbl_extruder_purging_details', sa.Column('resin_id', sa.SmallInteger(), nullable=False))
    op.add_column('tbl_extruder_purging_details', sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tbl_extruder_purging_details', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tbl_extruder_purging_details', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_extruder_purging_details', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_purging_details', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_purging_details', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_purging_details', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_extruder_purging_details', 'users', ['deleted_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_purging_details', 'users', ['created_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_purging_details', 'users', ['updated_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_purging_details', 'tbl_extruder_resins', ['resin_id'], ['id'])
    op.add_column('tbl_extruder_purging_headers', sa.Column('product_code', sa.String(length=100), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('time_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('time_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('resin_used_id', sa.SmallInteger(), nullable=False))
    op.add_column('tbl_extruder_purging_headers', sa.Column('palletizer_used', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('siever_used', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tbl_extruder_purging_headers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_extruder_purging_headers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_purging_headers', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_extruder_purging_headers', 'tbl_extruder_resins', ['resin_used_id'], ['id'])
    op.create_foreign_key(None, 'tbl_extruder_purging_headers', 'users', ['deleted_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_purging_headers', 'users', ['updated_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_purging_headers', 'users', ['created_by_id'], ['user_id'])
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_constraint(None, 'tbl_extruder_purging_headers', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_purging_headers', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_purging_headers', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_purging_headers', type_='foreignkey')
    op.drop_column('tbl_extruder_purging_headers', 'deleted_by_id')
    op.drop_column('tbl_extruder_purging_headers', 'updated_by_id')
    op.drop_column('tbl_extruder_purging_headers', 'created_by_id')
    op.drop_column('tbl_extruder_purging_headers', 'updated_at')
    op.drop_column('tbl_extruder_purging_headers', 'created_at')
    op.drop_column('tbl_extruder_purging_headers', 'is_deleted')
    op.drop_column('tbl_extruder_purging_headers', 'siever_used')
    op.drop_column('tbl_extruder_purging_headers', 'palletizer_used')
    op.drop_column('tbl_extruder_purging_headers', 'resin_used_id')
    op.drop_column('tbl_extruder_purging_headers', 'time_end')
    op.drop_column('tbl_extruder_purging_headers', 'time_start')
    op.drop_column('tbl_extruder_purging_headers', 'product_code')
    op.drop_constraint(None, 'tbl_extruder_purging_details', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_purging_details', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_purging_details', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_purging_details', type_='foreignkey')
    op.drop_column('tbl_extruder_purging_details', 'deleted_by_id')
    op.drop_column('tbl_extruder_purging_details', 'updated_by_id')
    op.drop_column('tbl_extruder_purging_details', 'created_by_id')
    op.drop_column('tbl_extruder_purging_details', 'updated_at')
    op.drop_column('tbl_extruder_purging_details', 'created_at')
    op.drop_column('tbl_extruder_purging_details', 'is_deleted')
    op.drop_column('tbl_extruder_purging_details', 'qty')
    op.drop_column('tbl_extruder_purging_details', 'resin_id')
    op.drop_constraint(None, 'tbl_extruder_personnels', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_personnels', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_personnels', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_personnels', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_personnels', type_='foreignkey')
    op.drop_column('tbl_extruder_personnels', 'deleted_by_id')
    op.drop_column('tbl_extruder_personnels', 'updated_by_id')
    op.drop_column('tbl_extruder_personnels', 'created_by_id')
    op.drop_column('tbl_extruder_personnels', 'updated_at')
    op.drop_column('tbl_extruder_personnels', 'created_at')
    op.drop_column('tbl_extruder_personnels', 'is_deleted')
    op.drop_column('tbl_extruder_personnels', 'position_id')
    op.drop_column('tbl_extruder_personnels', 'employee_id')
    op.drop_constraint(None, 'tbl_extruder_outputs', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_outputs', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_outputs', type_='foreignkey')
    op.drop_column('tbl_extruder_outputs', 'deleted_by_id')
    op.drop_column('tbl_extruder_outputs', 'updated_by_id')
    op.drop_column('tbl_extruder_outputs', 'created_by_id')
    op.drop_column('tbl_extruder_outputs', 'updated_at')
    op.drop_column('tbl_extruder_outputs', 'created_at')
    op.drop_column('tbl_extruder_outputs', 'is_deleted')
    op.drop_column('tbl_extruder_outputs', 'qty_loss')
    op.drop_column('tbl_extruder_outputs', 'qty_output')
    op.drop_column('tbl_extruder_outputs', 'time_end')
    op.drop_column('tbl_extruder_outputs', 'time_start')
    op.drop_constraint(None, 'tbl_extruder_machine_temps', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_machine_temps', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_machine_temps', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_machine_temps', type_='foreignkey')
    op.drop_column('tbl_extruder_machine_temps', 'deleted_by_id')
    op.drop_column('tbl_extruder_machine_temps', 'updated_by_id')
    op.drop_column('tbl_extruder_machine_temps', 'created_by_id')
    op.drop_column('tbl_extruder_machine_temps', 'updated_at')
    op.drop_column('tbl_extruder_machine_temps', 'created_at')
    op.drop_column('tbl_extruder_machine_temps', 'is_deleted')
    op.drop_column('tbl_extruder_machine_temps', 'temp_value')
    op.drop_column('tbl_extruder_machine_temps', 'zone_id')
    op.add_column('tbl_extruder_form_data', sa.Column('total_input', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_form_data', sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tbl_extruder_form_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_form_data', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_extruder_form_data_machine_id_fkey'), 'tbl_extruder_form_data', 'tbl_extruder_machines', ['machine_id'], ['id'])
    op.drop_column('tbl_extruder_form_data', 'shift_id')
    op.drop_column('tbl_extruder_form_data', 'machine_details_id')
    op.drop_column('tbl_extruder_form_data', 'qty_produced')
    op.create_table('tbl_extruder_machine_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('screen_size_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('screw_config', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('feed_rate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rpm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('tbl_extruder_machine_configs_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], name=op.f('tbl_extruder_machine_configs_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], name=op.f('tbl_extruder_machine_configs_extruder_form_data_id_fkey')),
    sa.ForeignKeyConstraint(['screen_size_id'], ['tbl_extruder_screen_sizes.id'], name=op.f('tbl_extruder_machine_configs_screen_size_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], name=op.f('tbl_extruder_machine_configs_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_extruder_machine_configs_pkey'))
    )
    op.drop_table('tbl_extruder_machine_details')
    # ### end Alembic commands ###
