"""tbl_prod02: Created a tbl_prod02 table in the database

Revision ID: 5fb850c46f28
Revises: c4413325cdfe
Create Date: 2025-10-16 14:36:00.231658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb850c46f28'
down_revision: Union[str, Sequence[str], None] = 'c4413325cdfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_prod02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_PRODID', sa.Numeric(), nullable=True),
    sa.Column('T_LOTNUM', sa.String(length=15), nullable=True),
    sa.Column('T_CDATE', sa.Date(), nullable=True),
    sa.Column('T_PRODDATE', sa.Date(), nullable=True),
    sa.Column('T_SEQ', sa.Integer(), nullable=True),
    sa.Column('T_MATCODE', sa.String(length=16), nullable=True),
    sa.Column('T_PRODA', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_LABA', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_PRODB', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_LABB', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_WT', sa.Numeric(precision=18, scale=7), nullable=True),
    sa.Column('T_LOSS', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_CONS', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_table('tbl_prod02', schema='public')
    # ### end Alembic commands ###
