"""tbl_extruder_machine_details: Added is_vacumeon column

Revision ID: 63d4f278602c
Revises: 58818c0ed744
Create Date: 2025-10-22 11:05:56.096351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d4f278602c'
down_revision: Union[str, Sequence[str], None] = '58818c0ed744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_form_data', sa.Column('machine_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tbl_extruder_form_data_machine_details_id_fkey'), 'tbl_extruder_form_data', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_extruder_form_data', 'tbl_extruder_machines', ['machine_id'], ['id'])
    op.drop_column('tbl_extruder_form_data', 'machine_details_id')
    op.add_column('tbl_extruder_machine_details', sa.Column('is_vacumeon', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_column('tbl_extruder_machine_details', 'is_vacumeon')
    op.add_column('tbl_extruder_form_data', sa.Column('machine_details_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tbl_extruder_form_data', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_extruder_form_data_machine_details_id_fkey'), 'tbl_extruder_form_data', 'tbl_extruder_machine_details', ['machine_details_id'], ['id'])
    op.drop_column('tbl_extruder_form_data', 'machine_id')
    # ### end Alembic commands ###
