"""Creating the Production Database

Revision ID: 6b0e57a15075
Revises: dd5edc657a93
Create Date: 2025-08-11 11:51:06.039048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0e57a15075'
down_revision: Union[str, Sequence[str], None] = 'dd5edc657a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_formula01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_UID', sa.Integer(), nullable=False),
    sa.Column('T_INDEX', sa.String(length=255), nullable=True),
    sa.Column('T_DATE', sa.Date(), nullable=True),
    sa.Column('T_CUSTOMER', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCODE', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCOLO', sa.String(length=255), nullable=True),
    sa.Column('T_DOSAGE', sa.Numeric(), nullable=True),
    sa.Column('T_LD', sa.Numeric(), nullable=True),
    sa.Column('T_MIX', sa.String(length=255), nullable=True),
    sa.Column('T_RESIN', sa.String(length=255), nullable=True),
    sa.Column('T_APP', sa.String(length=255), nullable=True),
    sa.Column('T_CMNUM', sa.String(length=255), nullable=True),
    sa.Column('T_CMDATE', sa.Date(), nullable=True),
    sa.Column('T_MATCHBY', sa.String(length=255), nullable=True),
    sa.Column('T_ENCODEDB', sa.String(length=255), nullable=True),
    sa.Column('T_REM', sa.String(length=255), nullable=True),
    sa.Column('T_TOTALCON', sa.Numeric(), nullable=True),
    sa.Column('T_USER', sa.String(length=255), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.Column('T_USED', sa.Boolean(), nullable=True),
    sa.Column('T_UPDATEBY', sa.String(length=255), nullable=True),
    sa.Column('T_UDATE', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tbl_formula02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_UID', sa.Integer(), nullable=False),
    sa.Column('T_SEQ', sa.Integer(), nullable=False),
    sa.Column('T_MATCODE', sa.String(length=255), nullable=True),
    sa.Column('T_CON', sa.Numeric(), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.Column('T_UPDATEBY', sa.String(length=255), nullable=True),
    sa.Column('T_UDATE', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tbl_prod01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_PRODID', sa.Numeric(), nullable=False),
    sa.Column('T_PRODDATE', sa.Date(), nullable=True),
    sa.Column('T_CUSTOMER', sa.String(length=255), nullable=True),
    sa.Column('T_FID', sa.Integer(), nullable=True),
    sa.Column('T_INDEX', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCODE', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCOLO', sa.String(length=255), nullable=True),
    sa.Column('T_DOSAGE', sa.Numeric(), nullable=True),
    sa.Column('T_LD', sa.Numeric(), nullable=True),
    sa.Column('T_LOTNUM', sa.String(length=255), nullable=True),
    sa.Column('T_ORDERNUM', sa.String(length=255), nullable=True),
    sa.Column('T_CMNUM', sa.String(length=255), nullable=True),
    sa.Column('T_CMDATE', sa.Date(), nullable=True),
    sa.Column('T_MIXTIME', sa.String(length=255), nullable=True),
    sa.Column('T_MACHINE', sa.String(length=255), nullable=True),
    sa.Column('T_QTYREQ', sa.Numeric(), nullable=True),
    sa.Column('T_QTYBATCH', sa.Numeric(), nullable=True),
    sa.Column('T_QTYPROD', sa.Numeric(), nullable=True),
    sa.Column('T_REMARKS', sa.String(length=255), nullable=True),
    sa.Column('T_NOTE', sa.String(length=255), nullable=True),
    sa.Column('T_USERID', sa.String(length=255), nullable=True),
    sa.Column('T_PREPARED', sa.String(length=255), nullable=True),
    sa.Column('T_ENCODEDB', sa.String(length=255), nullable=True),
    sa.Column('T_ENCODEDO', sa.String(length=255), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.Column('T_JDONE', sa.String(length=255), nullable=True),
    sa.Column('T_CDATE', sa.Date(), nullable=True),
    sa.Column('T_SDATE', sa.String(length=255), nullable=True),
    sa.Column('T_FTYPE', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_prod01', schema='public')
    op.drop_table('tbl_formula02', schema='public')
    op.drop_table('tbl_formula01', schema='public')
    # ### end Alembic commands ###
