"""Extruder Form Tables: Modified some table names

Revision ID: 74399be06523
Revises: ad585c124898
Create Date: 2025-10-09 16:22:24.027100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74399be06523'
down_revision: Union[str, Sequence[str], None] = 'ad585c124898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_extruder_screen_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_screen_sizes_size'), 'tbl_extruder_screen_sizes', ['size'], unique=True)
    op.create_table('tbl_extruder_machine_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('screen_size_id', sa.Integer(), nullable=False),
    sa.Column('screw_config', sa.String(length=255), nullable=True),
    sa.Column('feed_rate', sa.String(length=100), nullable=True),
    sa.Column('rpm', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['screen_size_id'], ['tbl_extruder_screen_sizes.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_extruder_machine_temps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('temp_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['tbl_extruder_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_extruder_purging_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resin_id', sa.SmallInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['resin_id'], ['tbl_extruder_resins.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tbl_machine_configs')
    op.drop_table('tbl_purging_details')
    op.drop_table('tbl_machine_temps')
    op.drop_index(op.f('ix_tbl_screen_sizes_size'), table_name='tbl_screen_sizes')
    op.drop_table('tbl_screen_sizes')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.create_table('tbl_screen_sizes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tbl_screen_sizes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name='tbl_screen_sizes_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], name='tbl_screen_sizes_deleted_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], name='tbl_screen_sizes_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tbl_screen_sizes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tbl_screen_sizes_size'), 'tbl_screen_sizes', ['size'], unique=True)
    op.create_table('tbl_machine_temps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temp_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('tbl_machine_temps_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], name=op.f('tbl_machine_temps_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], name=op.f('tbl_machine_temps_extruder_form_data_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], name=op.f('tbl_machine_temps_updated_by_id_fkey')),
    sa.ForeignKeyConstraint(['zone_id'], ['tbl_extruder_zones.id'], name=op.f('tbl_machine_temps_zone_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_machine_temps_pkey'))
    )
    op.create_table('tbl_purging_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('time_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resin_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('tbl_purging_details_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], name=op.f('tbl_purging_details_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], name=op.f('tbl_purging_details_extruder_form_data_id_fkey')),
    sa.ForeignKeyConstraint(['resin_id'], ['tbl_extruder_resins.id'], name=op.f('tbl_purging_details_resin_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], name=op.f('tbl_purging_details_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_purging_details_pkey'))
    )
    op.create_table('tbl_machine_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('screen_size_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('screw_config', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('feed_rate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rpm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('tbl_machine_configs_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], name=op.f('tbl_machine_configs_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], name=op.f('tbl_machine_configs_extruder_form_data_id_fkey')),
    sa.ForeignKeyConstraint(['screen_size_id'], ['tbl_screen_sizes.id'], name=op.f('tbl_machine_configs_screen_size_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], name=op.f('tbl_machine_configs_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_machine_configs_pkey'))
    )
    op.drop_table('tbl_extruder_purging_details')
    op.drop_table('tbl_extruder_machine_temps')
    op.drop_table('tbl_extruder_machine_configs')
    op.drop_index(op.f('ix_tbl_extruder_screen_sizes_size'), table_name='tbl_extruder_screen_sizes')
    op.drop_table('tbl_extruder_screen_sizes')
    # ### end Alembic commands ###
