"""modify: removed auditmixin

Revision ID: 830ab1debb47
Revises: 93341d8c956d
Create Date: 2025-11-25 13:27:03.550706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '830ab1debb47'
down_revision: Union[str, Sequence[str], None] = '93341d8c956d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbl_extruder_old_excel_data_created_by_id_fkey'), 'tbl_extruder_old_excel_data', type_='foreignkey')
    op.drop_constraint(op.f('tbl_extruder_old_excel_data_deleted_by_id_fkey'), 'tbl_extruder_old_excel_data', type_='foreignkey')
    op.drop_constraint(op.f('tbl_extruder_old_excel_data_updated_by_id_fkey'), 'tbl_extruder_old_excel_data', type_='foreignkey')
    op.drop_column('tbl_extruder_old_excel_data', 'updated_at')
    op.drop_column('tbl_extruder_old_excel_data', 'created_at')
    op.drop_column('tbl_extruder_old_excel_data', 'is_deleted')
    op.drop_column('tbl_extruder_old_excel_data', 'deleted_by_id')
    op.drop_column('tbl_extruder_old_excel_data', 'updated_by_id')
    op.drop_column('tbl_extruder_old_excel_data', 'created_by_id')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.add_column('tbl_extruder_old_excel_data', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tbl_extruder_old_excel_data_updated_by_id_fkey'), 'tbl_extruder_old_excel_data', 'users', ['updated_by_id'], ['user_id'])
    op.create_foreign_key(op.f('tbl_extruder_old_excel_data_deleted_by_id_fkey'), 'tbl_extruder_old_excel_data', 'users', ['deleted_by_id'], ['user_id'])
    op.create_foreign_key(op.f('tbl_extruder_old_excel_data_created_by_id_fkey'), 'tbl_extruder_old_excel_data', 'users', ['created_by_id'], ['user_id'])
    # ### end Alembic commands ###
