"""Extruder Form Tables: Modified the tbl_used_materials table name into tbl_extruder_used_materials

Revision ID: 8648d07bb55c
Revises: 74399be06523
Create Date: 2025-10-10 11:11:01.508856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8648d07bb55c'
down_revision: Union[str, Sequence[str], None] = '74399be06523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_extruder_used_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tbl_used_materials')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.create_table('tbl_used_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('formula_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('tbl_used_materials_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], name=op.f('tbl_used_materials_deleted_by_id_fkey')),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], name=op.f('tbl_used_materials_extruder_form_data_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], name=op.f('tbl_used_materials_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_used_materials_pkey'))
    )
    op.drop_table('tbl_extruder_used_materials')
    # ### end Alembic commands ###
