"""tbl_purging tables: Modified the Table and added tbl_extruder_purging_details table

Revision ID: 873bc93c9508
Revises: 5fb850c46f28
Create Date: 2025-10-20 08:39:27.960681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '873bc93c9508'
down_revision: Union[str, Sequence[str], None] = '5fb850c46f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_extruder_purging_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resin_used_id', sa.SmallInteger(), nullable=False),
    sa.Column('palletizer_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('siever_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['resin_used_id'], ['tbl_extruder_resins.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('tbl_extruder_purging_details_extruder_form_data_id_fkey'), 'tbl_extruder_purging_details', type_='foreignkey')
    op.drop_column('tbl_extruder_purging_details', 'product_code')
    op.drop_column('tbl_extruder_purging_details', 'time_end')
    op.drop_column('tbl_extruder_purging_details', 'time_start')
    op.drop_column('tbl_extruder_purging_details', 'extruder_form_data_id')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.add_column('tbl_extruder_purging_details', sa.Column('extruder_form_data_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tbl_extruder_purging_details', sa.Column('time_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_purging_details', sa.Column('time_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_purging_details', sa.Column('product_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tbl_extruder_purging_details_extruder_form_data_id_fkey'), 'tbl_extruder_purging_details', 'tbl_extruder_form_data', ['extruder_form_data_id'], ['id'])
    op.drop_table('tbl_extruder_purging_headers')
    # ### end Alembic commands ###
