"""tbl_extruder_outputs: Removed date column and moditied time start and time end from Time into DateTime

Revision ID: 8cb6cd5fc6aa
Revises: 5798da5ea448
Create Date: 2025-10-25 08:33:10.934502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb6cd5fc6aa'
down_revision: Union[str, Sequence[str], None] = '5798da5ea448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_outputs', sa.Column('datetime_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('datetime_end', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tbl_extruder_outputs', 'time_start')
    op.drop_column('tbl_extruder_outputs', 'date')
    op.drop_column('tbl_extruder_outputs', 'time_end')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.add_column('tbl_extruder_outputs', sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tbl_extruder_outputs', sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('tbl_extruder_outputs', 'datetime_end')
    op.drop_column('tbl_extruder_outputs', 'datetime_start')
    # ### end Alembic commands ###
