"""modify: rpm change datatype

Revision ID: 93341d8c956d
Revises: 9bd7f3faf799
Create Date: 2025-11-25 13:26:17.610457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93341d8c956d'
down_revision: Union[str, Sequence[str], None] = '9bd7f3faf799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_old_excel_data', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('tbl_extruder_old_excel_data', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.alter_column('tbl_extruder_old_excel_data', 'rpm',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_tbl_extruder_old_excel_data_rpm'), 'tbl_extruder_old_excel_data', ['rpm'], unique=False)
    op.create_foreign_key(None, 'tbl_extruder_old_excel_data', 'users', ['updated_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_old_excel_data', 'users', ['created_by_id'], ['user_id'])
    op.create_foreign_key(None, 'tbl_extruder_old_excel_data', 'users', ['deleted_by_id'], ['user_id'])
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_constraint(None, 'tbl_extruder_old_excel_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_old_excel_data', type_='foreignkey')
    op.drop_constraint(None, 'tbl_extruder_old_excel_data', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_extruder_old_excel_data_rpm'), table_name='tbl_extruder_old_excel_data')
    op.alter_column('tbl_extruder_old_excel_data', 'rpm',
               existing_type=sa.String(length=10),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('tbl_extruder_old_excel_data', 'deleted_by_id')
    op.drop_column('tbl_extruder_old_excel_data', 'updated_by_id')
    op.drop_column('tbl_extruder_old_excel_data', 'created_by_id')
    op.drop_column('tbl_extruder_old_excel_data', 'updated_at')
    op.drop_column('tbl_extruder_old_excel_data', 'created_at')
    op.drop_column('tbl_extruder_old_excel_data', 'is_deleted')
    # ### end Alembic commands ###
