"""tbl_resins: Added 'abbreviation' column to the table

Revision ID: 9d96217f884f
Revises: 1398ba93aea1
Create Date: 2025-09-27 15:40:51.121105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d96217f884f'
down_revision: Union[str, Sequence[str], None] = '1398ba93aea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_resins', sa.Column('abbreviation', sa.String(length=10), nullable=True))
    op.alter_column('tbl_extruder_resins', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_tbl_extruder_resins_abbreviation'), 'tbl_extruder_resins', ['abbreviation'], unique=True)
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_index(op.f('ix_tbl_extruder_resins_abbreviation'), table_name='tbl_extruder_resins')
    op.alter_column('tbl_extruder_resins', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tbl_extruder_resins', 'abbreviation')
    # ### end Alembic commands ###
