"""Extruder Form Tables: Create all the tables for the Extruder Form

Revision ID: ad585c124898
Revises: 9d96217f884f
Create Date: 2025-10-09 16:11:38.527005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad585c124898'
down_revision: Union[str, Sequence[str], None] = '9d96217f884f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_customers_name'), 'tbl_customers', ['name'], unique=True)
    op.create_table('tbl_employee_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_employee_positions_name'), 'tbl_employee_positions', ['name'], unique=True)
    op.create_table('tbl_production_employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_screen_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_screen_sizes_size'), 'tbl_screen_sizes', ['size'], unique=True)
    op.create_table('tbl_extruder_form_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.String(length=100), nullable=True),
    sa.Column('production_id', sa.String(length=100), nullable=True),
    sa.Column('formula_no', sa.String(length=100), nullable=True),
    sa.Column('order_no', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('qty_order', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_input', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('prepared_by', sa.String(length=255), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_datetime_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('machine_datetime_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['tbl_customers.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['tbl_extruder_machines.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_form_data_lot_number'), 'tbl_extruder_form_data', ['lot_number'], unique=False)
    op.create_index(op.f('ix_tbl_extruder_form_data_process_id'), 'tbl_extruder_form_data', ['process_id'], unique=False)
    op.create_index(op.f('ix_tbl_extruder_form_data_production_id'), 'tbl_extruder_form_data', ['production_id'], unique=False)
    op.create_table('tbl_extruder_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qty_output', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qty_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_extruder_personnels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['tbl_production_employees.id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['tbl_employee_positions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_machine_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('screen_size_id', sa.Integer(), nullable=False),
    sa.Column('screw_config', sa.String(length=255), nullable=True),
    sa.Column('feed_rate', sa.String(length=100), nullable=True),
    sa.Column('rpm', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['screen_size_id'], ['tbl_screen_sizes.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_machine_temps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('temp_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['tbl_extruder_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_purging_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resin_id', sa.SmallInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['resin_id'], ['tbl_extruder_resins.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_used_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extruder_form_data_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['extruder_form_data_id'], ['tbl_extruder_form_data.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_table('tbl_used_materials')
    op.drop_table('tbl_purging_details')
    op.drop_table('tbl_machine_temps')
    op.drop_table('tbl_machine_configs')
    op.drop_table('tbl_extruder_personnels')
    op.drop_table('tbl_extruder_outputs')
    op.drop_index(op.f('ix_tbl_extruder_form_data_production_id'), table_name='tbl_extruder_form_data')
    op.drop_index(op.f('ix_tbl_extruder_form_data_process_id'), table_name='tbl_extruder_form_data')
    op.drop_index(op.f('ix_tbl_extruder_form_data_lot_number'), table_name='tbl_extruder_form_data')
    op.drop_table('tbl_extruder_form_data')
    op.drop_index(op.f('ix_tbl_screen_sizes_size'), table_name='tbl_screen_sizes')
    op.drop_table('tbl_screen_sizes')
    op.drop_table('tbl_production_employees')
    op.drop_index(op.f('ix_tbl_employee_positions_name'), table_name='tbl_employee_positions')
    op.drop_table('tbl_employee_positions')
    op.drop_index(op.f('ix_tbl_customers_name'), table_name='tbl_customers')
    op.drop_table('tbl_customers')
    # ### end Alembic commands ###
