"""modify: qty input change data type

Revision ID: b5bb7fbb629e
Revises: 886379c79e44
Create Date: 2025-11-25 13:47:28.777093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5bb7fbb629e'
down_revision: Union[str, Sequence[str], None] = '886379c79e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_extruder_old_excel_data', 'qty_input',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.alter_column('tbl_extruder_old_excel_data', 'qty_input',
               existing_type=sa.String(length=15),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
