"""modify: zone datatype

Revision ID: b8933e22a41c
Revises: 830ab1debb47
Create Date: 2025-11-25 13:30:07.010490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8933e22a41c'
down_revision: Union[str, Sequence[str], None] = '830ab1debb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_extruder_old_excel_data', 'z1',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z2',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z3',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z4',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z5',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z6',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z7',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z8',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z9',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z10',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z11',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z12',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z13',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.alter_column('tbl_extruder_old_excel_data', 'z13',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z12',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z11',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z10',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z9',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z8',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z7',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z6',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z5',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z4',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z3',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z2',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_old_excel_data', 'z1',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
