"""tbl_extruder_screw_config: Created thi table

Revision ID: c0abbbd21168
Revises: 4c23ea3eed67
Create Date: 2025-10-22 11:19:24.822319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0abbbd21168'
down_revision: Union[str, Sequence[str], None] = '4c23ea3eed67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_machine_details', sa.Column('screw_config_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tbl_extruder_machine_details', 'tbl_extruder_screw_configs', ['screw_config_id'], ['id'])
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_constraint(None, 'tbl_extruder_machine_details', type_='foreignkey')
    op.drop_column('tbl_extruder_machine_details', 'screw_config_id')
    # ### end Alembic commands ###
