"""tbl_extruder_form_data: Modified the customer column from fk into varchar(500)

Revision ID: c4413325cdfe
Revises: 2f79492dd51c
Create Date: 2025-10-14 11:37:12.751392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4413325cdfe'
down_revision: Union[str, Sequence[str], None] = '2f79492dd51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_form_data', sa.Column('customer', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('tbl_extruder_form_data_customer_id_fkey'), 'tbl_extruder_form_data', type_='foreignkey')
    op.drop_column('tbl_extruder_form_data', 'customer_id')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.add_column('tbl_extruder_form_data', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tbl_extruder_form_data_customer_id_fkey'), 'tbl_extruder_form_data', 'tbl_customers', ['customer_id'], ['id'])
    op.drop_column('tbl_extruder_form_data', 'customer')
    # ### end Alembic commands ###
