"""Creating the Production Database

Revision ID: c45ad4bd2864
Revises: 6b0e57a15075
Create Date: 2025-08-11 13:20:46.680089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45ad4bd2864'
down_revision: Union[str, Sequence[str], None] = '6b0e57a15075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_formula02', sa.Column('formula_header_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.drop_column('tbl_formula02', 'formula_header_id')
    # ### end Alembic commands ###
