"""tlb_incoming2: Created a table tbl_incoming2

Revision ID: c6127453c9bb
Revises: f22368a754e6
Create Date: 2025-10-21 11:47:16.644713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6127453c9bb'
down_revision: Union[str, Sequence[str], None] = 'f22368a754e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('tbl_incoming2', sa.Column('t_seq', sa.Integer(), nullable=True))
    op.drop_column('tbl_incoming2', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_incoming2', sa.Column('note', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tbl_incoming2', 't_seq')
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    # ### end Alembic commands ###
