"""Mixer Tables Added

Revision ID: cad9c9a9fbcf
Revises: 
Create Date: 2025-07-26 14:19:03.741925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad9c9a9fbcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_mixer_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tbl_mixer_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, unique=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('workstation_name', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'USER', 'DISABLED', name='userrole'), nullable=False),
    sa.Column('department', sa.Enum('IT', 'WAREHOUSE', 'PRODUCTION', 'LAB', name='department'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('auth_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('tbl_mixer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('lot_no', sa.String(length=50), nullable=False),
    sa.Column('lot_count', sa.SmallInteger(), nullable=False),
    sa.Column('process_time_start', sa.Time(), nullable=True),
    sa.Column('process_time_end', sa.Time(), nullable=True),
    sa.Column('processed_by', sa.String(length=20), nullable=False),
    sa.Column('output_qty', sa.Float(), nullable=False),
    sa.Column('cleaning_time_start', sa.Time(), nullable=False),
    sa.Column('cleaning_time_end', sa.Time(), nullable=False),
    sa.Column('cleaning_rm_code', sa.String(length=30), nullable=False),
    sa.Column('cleaning_qty', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('mc_id', sa.Integer(), nullable=False),
    sa.Column('mixer_header_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mc_id'], ['tbl_mixer_machines.id'], ),
    sa.ForeignKeyConstraint(['mixer_header_id'], ['tbl_mixer_headers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_mixer_details')
    op.drop_table('auth_logs')
    op.drop_table('users')
    op.drop_table('tbl_mixer_machines')
    op.drop_table('tbl_mixer_headers')
    # ### end Alembic commands ###
