"""Cretion Other Tables

Revision ID: d6b3f3f7bb87
Revises: 
Create Date: 2025-10-22 10:01:47.394071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b3f3f7bb87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_tbl_mixer_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_table('tbl_formula01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_UID', sa.Integer(), nullable=False),
    sa.Column('T_INDEX', sa.String(length=255), nullable=True),
    sa.Column('T_DATE', sa.Date(), nullable=True),
    sa.Column('T_CUSTOMER', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCODE', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCOLO', sa.String(length=255), nullable=True),
    sa.Column('T_DOSAGE', sa.Numeric(), nullable=True),
    sa.Column('T_LD', sa.Numeric(), nullable=True),
    sa.Column('T_MIX', sa.String(length=255), nullable=True),
    sa.Column('T_RESIN', sa.String(length=255), nullable=True),
    sa.Column('T_APP', sa.String(length=255), nullable=True),
    sa.Column('T_CMNUM', sa.String(length=255), nullable=True),
    sa.Column('T_CMDATE', sa.Date(), nullable=True),
    sa.Column('T_MATCHBY', sa.String(length=255), nullable=True),
    sa.Column('T_ENCODEDB', sa.String(length=255), nullable=True),
    sa.Column('T_REM', sa.String(length=255), nullable=True),
    sa.Column('T_TOTALCON', sa.Numeric(), nullable=True),
    sa.Column('T_USER', sa.String(length=255), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.Column('T_USED', sa.Boolean(), nullable=True),
    sa.Column('T_UPDATEBY', sa.String(length=255), nullable=True),
    sa.Column('T_UDATE', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tbl_prod01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_PRODID', sa.Numeric(), nullable=False),
    sa.Column('T_PRODDATE', sa.Date(), nullable=True),
    sa.Column('T_CUSTOMER', sa.String(length=255), nullable=True),
    sa.Column('T_FID', sa.Integer(), nullable=True),
    sa.Column('T_INDEX', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCODE', sa.String(length=255), nullable=True),
    sa.Column('T_PRODCOLO', sa.String(length=255), nullable=True),
    sa.Column('T_DOSAGE', sa.Numeric(), nullable=True),
    sa.Column('T_LD', sa.Numeric(), nullable=True),
    sa.Column('T_LOTNUM', sa.String(length=255), nullable=True),
    sa.Column('T_ORDERNUM', sa.String(length=255), nullable=True),
    sa.Column('T_CMNUM', sa.String(length=255), nullable=True),
    sa.Column('T_CMDATE', sa.Date(), nullable=True),
    sa.Column('T_MIXTIME', sa.String(length=255), nullable=True),
    sa.Column('T_MACHINE', sa.String(length=255), nullable=True),
    sa.Column('T_QTYREQ', sa.Numeric(), nullable=True),
    sa.Column('T_QTYBATCH', sa.Numeric(), nullable=True),
    sa.Column('T_QTYPROD', sa.Numeric(), nullable=True),
    sa.Column('T_REMARKS', sa.String(length=255), nullable=True),
    sa.Column('T_NOTE', sa.String(length=255), nullable=True),
    sa.Column('T_USERID', sa.String(length=255), nullable=True),
    sa.Column('T_PREPARED', sa.String(length=255), nullable=True),
    sa.Column('T_ENCODEDB', sa.String(length=255), nullable=True),
    sa.Column('T_ENCODEDO', sa.String(length=255), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.Column('T_JDONE', sa.String(length=255), nullable=True),
    sa.Column('T_CDATE', sa.Date(), nullable=True),
    sa.Column('T_SDATE', sa.String(length=255), nullable=True),
    sa.Column('T_FTYPE', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tbl_prod02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_PRODID', sa.Numeric(), nullable=True),
    sa.Column('T_LOTNUM', sa.String(length=15), nullable=True),
    sa.Column('T_CDATE', sa.Date(), nullable=True),
    sa.Column('T_PRODDATE', sa.Date(), nullable=True),
    sa.Column('T_SEQ', sa.Integer(), nullable=True),
    sa.Column('T_MATCODE', sa.String(length=16), nullable=True),
    sa.Column('T_PRODA', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_LABA', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_PRODB', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_LABB', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_WT', sa.Numeric(precision=18, scale=7), nullable=True),
    sa.Column('T_LOSS', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_CONS', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tbl_raw_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rm_code', sa.String(length=50), nullable=False),
    sa.Column('rm_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rm_code'),
    schema='public'
    )
    op.create_table('tbl_incoming2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_seq', sa.Integer(), nullable=True),
    sa.Column('t_ctrlnum', sa.String(length=100), nullable=True),
    sa.Column('t_date', sa.Date(), nullable=True),
    sa.Column('t_matcode', sa.String(length=15), nullable=True),
    sa.Column('t_qty', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('t_note', sa.String(length=254), nullable=True),
    sa.Column('t_uid', sa.String(length=100), nullable=True),
    sa.Column('t_deleted', sa.Boolean(), nullable=True),
    sa.Column('t_customer', sa.String(length=100), nullable=True),
    sa.Column('t_code', sa.String(length=100), nullable=True),
    sa.Column('t_po', sa.String(length=100), nullable=True),
    sa.Column('t_datereq', sa.Date(), nullable=True),
    sa.Column('t_datereq2', sa.String(length=100), nullable=True),
    sa.Column('t_delto', sa.String(length=100), nullable=True),
    sa.Column('t_orderedb', sa.String(length=100), nullable=True),
    sa.Column('t_prepared', sa.String(length=100), nullable=True),
    sa.Column('t_mattype', sa.String(length=15), nullable=True),
    sa.Column('t_status', sa.String(length=30), nullable=True),
    sa.Column('t_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_mixer_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tbl_mixer_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('temp_tbl_mixer_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.BIGINT(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('workstation_name', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'USER', 'DISABLED', name='userrole'), nullable=False),
    sa.Column('department', sa.Enum('IT', 'WAREHOUSE', 'PRODUCTION', 'LAB', name='department'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('auth_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('old_tbl_mixer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('lot_no', sa.String(length=100), nullable=True),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['header_id'], ['old_tbl_mixer_headers.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['tbl_mixer_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_formula02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_header_id', sa.Integer(), nullable=False),
    sa.Column('T_UID', sa.Integer(), nullable=False),
    sa.Column('T_SEQ', sa.Integer(), nullable=False),
    sa.Column('T_MATCODE', sa.String(length=255), nullable=True),
    sa.Column('T_CON', sa.Numeric(), nullable=True),
    sa.Column('T_DELETED', sa.Boolean(), nullable=True),
    sa.Column('T_UPDATEBY', sa.String(length=255), nullable=True),
    sa.Column('T_UDATE', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['formula_header_id'], ['public.tbl_formula01.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tbl_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_customers_name'), 'tbl_customers', ['name'], unique=True)
    op.create_table('tbl_employee_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_employee_positions_name'), 'tbl_employee_positions', ['name'], unique=True)
    op.create_table('tbl_extruder_machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_machines_name'), 'tbl_extruder_machines', ['name'], unique=True)
    op.create_table('tbl_extruder_resins',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_resins_abbreviation'), 'tbl_extruder_resins', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_tbl_extruder_resins_name'), 'tbl_extruder_resins', ['name'], unique=True)
    op.create_table('tbl_extruder_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_extruder_zones_name'), 'tbl_extruder_zones', ['name'], unique=True)
    op.create_table('tbl_mixer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('lot_no', sa.String(length=50), nullable=False),
    sa.Column('lot_count', sa.SmallInteger(), nullable=False),
    sa.Column('process_time_start', sa.Time(), nullable=True),
    sa.Column('process_time_end', sa.Time(), nullable=True),
    sa.Column('processed_by', sa.String(length=20), nullable=False),
    sa.Column('output_qty', sa.Float(), nullable=False),
    sa.Column('cleaning_time_start', sa.Time(), nullable=True),
    sa.Column('cleaning_time_end', sa.Time(), nullable=True),
    sa.Column('cleaning_rm_code', sa.String(length=30), nullable=True),
    sa.Column('cleaning_qty', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('mc_id', sa.Integer(), nullable=False),
    sa.Column('mixer_header_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mc_id'], ['tbl_mixer_machines.id'], ),
    sa.ForeignKeyConstraint(['mixer_header_id'], ['tbl_mixer_headers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tbl_production_employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_tbl_mixer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_header_id', sa.Integer(), nullable=False),
    sa.Column('mc_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('lot_no', sa.String(length=50), nullable=False),
    sa.Column('lot_count', sa.SmallInteger(), nullable=False),
    sa.Column('process_time_start', sa.Time(), nullable=True),
    sa.Column('process_time_end', sa.Time(), nullable=True),
    sa.Column('processed_by', sa.String(length=20), nullable=False),
    sa.Column('output_qty', sa.Float(), nullable=False),
    sa.Column('cleaning_time_start', sa.Time(), nullable=True),
    sa.Column('cleaning_time_end', sa.Time(), nullable=True),
    sa.Column('cleaning_rm_code', sa.String(length=30), nullable=True),
    sa.Column('cleaning_qty', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['temp_header_id'], ['temp_tbl_mixer_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_extruder_resin_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resin_id', sa.SmallInteger(), nullable=False),
    sa.Column('motor_rpm', sa.String(length=50), nullable=False),
    sa.Column('feed_rate', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['resin_id'], ['tbl_extruder_resins.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_extruder_processing_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('resin_params_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('temp_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['tbl_extruder_machines.id'], ),
    sa.ForeignKeyConstraint(['resin_params_id'], ['tbl_extruder_resin_params.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['tbl_extruder_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'resin_params_id', 'zone_id', name='_machine_resin_zone_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_extruder_processing_params')
    op.drop_table('tbl_extruder_resin_params')
    op.drop_table('temp_tbl_mixer_details')
    op.drop_table('tbl_production_employees')
    op.drop_table('tbl_mixer_details')
    op.drop_index(op.f('ix_tbl_extruder_zones_name'), table_name='tbl_extruder_zones')
    op.drop_table('tbl_extruder_zones')
    op.drop_index(op.f('ix_tbl_extruder_resins_name'), table_name='tbl_extruder_resins')
    op.drop_index(op.f('ix_tbl_extruder_resins_abbreviation'), table_name='tbl_extruder_resins')
    op.drop_table('tbl_extruder_resins')
    op.drop_index(op.f('ix_tbl_extruder_machines_name'), table_name='tbl_extruder_machines')
    op.drop_table('tbl_extruder_machines')
    op.drop_index(op.f('ix_tbl_employee_positions_name'), table_name='tbl_employee_positions')
    op.drop_table('tbl_employee_positions')
    op.drop_index(op.f('ix_tbl_customers_name'), table_name='tbl_customers')
    op.drop_table('tbl_customers')
    op.drop_table('tbl_formula02', schema='public')
    op.drop_table('old_tbl_mixer_details')
    op.drop_table('auth_logs')
    op.drop_table('users')
    op.drop_table('temp_tbl_mixer_headers')
    op.drop_table('tbl_mixer_machines')
    op.drop_table('tbl_mixer_headers')
    op.drop_table('tbl_incoming2')
    op.drop_table('tbl_raw_materials', schema='public')
    op.drop_table('tbl_prod02', schema='public')
    op.drop_table('tbl_prod01', schema='public')
    op.drop_table('tbl_formula01', schema='public')
    op.drop_table('old_tbl_mixer_headers')
    # ### end Alembic commands ###
