"""Created a Raw Material Table

Revision ID: d986b0f4d7b6
Revises: 84a5da75ce50
Create Date: 2025-08-13 15:34:05.853718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd986b0f4d7b6'
down_revision: Union[str, Sequence[str], None] = '84a5da75ce50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_raw_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rm_code', sa.String(length=50), nullable=False),
    sa.Column('rm_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rm_code'),
    schema='public'
    )
    op.alter_column('tbl_formula01', 'T_DOSAGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('tbl_formula01', 'T_TOTALCON',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('tbl_formula02', 'T_CON',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('tbl_prod01', 'T_DOSAGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('tbl_prod01', 'T_QTYREQ',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('tbl_prod01', 'T_QTYBATCH',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('tbl_prod01', 'T_QTYPROD',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_prod01', 'T_QTYPROD',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tbl_prod01', 'T_QTYBATCH',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tbl_prod01', 'T_QTYREQ',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tbl_prod01', 'T_DOSAGE',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.alter_column('tbl_formula02', 'T_CON',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tbl_formula01', 'T_TOTALCON',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tbl_formula01', 'T_DOSAGE',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_table('tbl_raw_materials', schema='public')
    # ### end Alembic commands ###
