"""Mixer Form Module: Creating temp table for mixer header and mixer tables

Revision ID: dd5edc657a93
Revises: cad9c9a9fbcf
Create Date: 2025-08-01 17:15:56.356255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5edc657a93'
down_revision: Union[str, Sequence[str], None] = 'cad9c9a9fbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_tbl_mixer_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.BIGINT(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('temp_tbl_mixer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_header_id', sa.Integer(), nullable=False),
    sa.Column('mc_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('lot_no', sa.String(length=50), nullable=False),
    sa.Column('lot_count', sa.SmallInteger(), nullable=False),
    sa.Column('process_time_start', sa.Time(), nullable=True),
    sa.Column('process_time_end', sa.Time(), nullable=True),
    sa.Column('processed_by', sa.String(length=20), nullable=False),
    sa.Column('output_qty', sa.Float(), nullable=False),
    sa.Column('cleaning_time_start', sa.Time(), nullable=False),
    sa.Column('cleaning_time_end', sa.Time(), nullable=False),
    sa.Column('cleaning_rm_code', sa.String(length=30), nullable=False),
    sa.Column('cleaning_qty', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['temp_header_id'], ['temp_tbl_mixer_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'tbl_mixer_details', ['id'])
    op.create_unique_constraint(None, 'tbl_mixer_headers', ['id'])
    op.create_unique_constraint(None, 'tbl_mixer_machines', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_mixer_machines', type_='unique')
    op.drop_constraint(None, 'tbl_mixer_headers', type_='unique')
    op.drop_constraint(None, 'tbl_mixer_details', type_='unique')
    op.drop_table('temp_tbl_mixer_details')
    op.drop_table('temp_tbl_mixer_headers')
    # ### end Alembic commands ###
