"""tbl_extruder_machine_details: Added is_vacumeon column

Revision ID: ed43ce427873
Revises: 63d4f278602c
Create Date: 2025-10-22 11:06:18.596823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed43ce427873'
down_revision: Union[str, Sequence[str], None] = '63d4f278602c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_extruder_machine_details', sa.Column('is_vaccumeon', sa.Boolean(), nullable=False))
    op.drop_column('tbl_extruder_machine_details', 'is_vacumeon')
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.add_column('tbl_extruder_machine_details', sa.Column('is_vacumeon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tbl_extruder_machine_details', 'is_vaccumeon')
    # ### end Alembic commands ###
