"""tlb_incoming2: Created a table tbl_incoming2

Revision ID: f22368a754e6
Revises: b3811b7ab4b8
Create Date: 2025-10-21 11:25:13.608336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22368a754e6'
down_revision: Union[str, Sequence[str], None] = 'b3811b7ab4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_incoming2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.Column('t_ctrlnum', sa.String(length=100), nullable=True),
    sa.Column('t_date', sa.Date(), nullable=True),
    sa.Column('t_matcode', sa.String(length=15), nullable=True),
    sa.Column('t_qty', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('t_note', sa.String(length=254), nullable=True),
    sa.Column('t_uid', sa.String(length=100), nullable=True),
    sa.Column('t_deleted', sa.Boolean(), nullable=True),
    sa.Column('t_customer', sa.String(length=100), nullable=True),
    sa.Column('t_code', sa.String(length=100), nullable=True),
    sa.Column('t_po', sa.String(length=100), nullable=True),
    sa.Column('t_datereq', sa.Date(), nullable=True),
    sa.Column('t_datereq2', sa.String(length=100), nullable=True),
    sa.Column('t_delto', sa.String(length=100), nullable=True),
    sa.Column('t_orderedb', sa.String(length=100), nullable=True),
    sa.Column('t_prepared', sa.String(length=100), nullable=True),
    sa.Column('t_mattype', sa.String(length=15), nullable=True),
    sa.Column('t_status', sa.String(length=30), nullable=True),
    sa.Column('t_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.drop_table('tbl_incoming2')
    # ### end Alembic commands ###
