"""COnvert DateTime Format into Time format for the the tables with time start and time end

Revision ID: fb0fb28405c5
Revises: 582757df6691
Create Date: 2025-10-24 16:36:00.763457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0fb28405c5'
down_revision: Union[str, Sequence[str], None] = '582757df6691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_extruder_outputs', 'time_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_outputs', 'time_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_purging_headers', 'time_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('tbl_extruder_purging_headers', 'time_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=True)
    op.drop_constraint(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_formula02', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_formula02_formula_header_id_fkey'), 'tbl_formula02', 'tbl_formula01', ['formula_header_id'], ['id'])
    op.alter_column('tbl_extruder_purging_headers', 'time_end',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tbl_extruder_purging_headers', 'time_start',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tbl_extruder_outputs', 'time_end',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tbl_extruder_outputs', 'time_start',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
